[package]
name = "mysql"
version = "21.0.3"
authors = ["blackbeam"]
description = "Mysql client library implemented in rust"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/mysql"
repository = "https://github.com/blackbeam/rust-mysql-simple"
keywords = ["database", "sql"]
exclude = ["tests/*", ".*", "Makefile"]
categories = ["database"]
edition = "2018"
build = "build.rs"

[badges.azure-devops]
build = "1"
pipeline = "blackbeam.rust-mysql-simple"
project = "aikorsky/mysql Rust"

[lib]
name = "mysql"
path = "src/lib.rs"

[profile.bench]
debug = true

[features]
default = ["native-tls","mysql_common/chrono", "mysql_common/time"]
rustls-tls = ["rustls", "webpki", "webpki-roots", "rustls-pemfile"]
nightly = []

[dev-dependencies]
lazy_static = "1.4.0"
rand = "0.8.2"
serde_derive = "1"

[dependencies]
bufstream = "~0.1"
bytes = "1.0.1"
io-enum = "1.0.0"
lru = "0.7.1"
mysql_common = { git = "https://github.com/readysettech/rust_mysql_common.git", branch = "zero-terminated-nonce" }
socket2 = "0.4"
once_cell = "1.7.2"
pem = "0.8.1"
percent-encoding = "2.1.0"
serde = "1"
serde_json = "1"
twox-hash = "1"
url = "2.1"

[dependencies.native-tls]
version = "0.2.3"
optional = true

[dependencies.rustls]
version = "0.20.0"
features = ["dangerous_configuration"]
optional = true

[dependencies.rustls-pemfile]
version = "0.2.1"
optional = true

[dependencies.webpki]
version = "0.22.0"
optional = true

[dependencies.webpki-roots]
version = "0.22.1"
optional = true

[target.'cfg(target_os = "windows")'.dependencies]
named_pipe = "~0.4"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
nix = "0.23.0"
